notifications:
  email:
    on_success: never
    #on_failure: always
    on_failure: never

services:
  - docker

env:
  - DEMYX_USERNAME=demyx DEMYX_REPOSITORY=scratch

before_install:
  - docker pull alpine
  - docker pull demyx/utilities

script:
  - cd docker && docker build --no-cache -t demyx/"$DEMYX_REPOSITORY" .
  - docker run -dt --rm --name demyx -v /var/run/docker.sock:/var/run/docker.sock:ro -v demyx:/demyx demyx/"$DEMYX_REPOSITORY"
  - sleep 5
  - docker exec -t demyx demyx motd

after_success:
  - echo "$DEMYX_PASSWORD" | docker login -u "$DEMYX_USERNAME" --password-stdin
  - docker push demyx/"$DEMYX_REPOSITORY"
  - cd .. && bash travis.sh
