# Demyx
# https://demyx.sh

notifications:
  email:
    on_success: never
    on_failure: never

services:
  - docker

before_install:
  - sudo mv dist_linux/docker-* /usr/local/bin

script:
  #- docker build -t demyx/logrotate .
  - sudo docker-slim build --http-probe=false --from-dockerfile=Dockerfile --tag=demyx/openlitespeed tag-latest
  - docker images
