sudo: required

dist: alpine

services:
  - docker

script:
  - echo "$DEMYX_PASSWORD" | docker login -u "$DEMYX_USERNAME" --password-stdin
  - docker build -t demyx/scratch .
  - docker run -dt --rm --name "$DEMYX_USERNAME" "$DEMYX_USERNAME"/scratch
  - docker exec -t "$DEMYX_USERNAME" ls -al /demyx/etc

#after_script:
#  - docker images

#before_deploy:
#  - echo "$DEMYX_PASSWORD" | docker login -u "$DEMYX_USERNAME" --password-stdin
#deploy:
#  provider: script
#  script: docker push "$DEMYX_USERNAME"/scratch
