# Demyx
# https://demyx.sh

notifications:
  email:
    on_success: never
    on_failure: never

arch:
  - amd64
  - arm64

services:
  - docker

env:
  - DEMYX_USERNAME=demyx DEMYX_REPOSITORY=eternal-terminal

before_install:
  - docker pull alpine

script:
  - docker buildx build --platform linux/arm/v7,linux/arm64/v8,linux/amd64 --tag demyx/"$DEMYX_REPOSITORY" .
  - docker image inspect demyx/"$DEMYX_REPOSITORY"
