# Demyx
# https://demyx.sh

notifications:
  email:
    on_success: never
    on_failure: never

services:
  - docker

before_install:
  - curl -sL https://github.com/docker-slim/docker-slim/releases/download/1.26.1/dist_linux.tar.gz -o /tmp/dist_linux.tar.gz
  - tar -xzf /tmp/dist_linux.tar.gz -C /tmp
  - sudo mv /tmp/dist_linux/docker-* /usr/local/bin

script:
  #- docker build -t demyx/logrotate .
  - docker-slim build --from-dockerfile=Dockerfile --tag=demyx/logrotate
  - docker images
