notifications:
  email:
    on_success: never
    on_failure: never

services:
  - docker

env:
  - DEMYX_USERNAME=demyx DEMYX_REPOSITORY=demyx DEMYX_VERSION=1.0.0

before_install:
  - docker pull demyx/docker-compose
  - docker pull demyx/docker-socket-proxy
  - docker pull demyx/mariadb
  - docker pull demyx/nginx
  - docker pull demyx/traefik
  - docker pull demyx/utilities
  - docker pull demyx/wordpress
  - docker pull demyx/wordpress:cli
  - docker pull alpine

script:
  - docker build --no-cache -t demyx/"$DEMYX_REPOSITORY" .
  - sudo cp host.sh /usr/local/bin/demyx
  - sudo chmod +x /usr/local/bin/demyx
  - sudo echo "DEMYX_HOST_INSTALL=false" > /root/.demyx
  - sudo demyx
  - sleep 10
  - sudo demyx run domain.tld
  - sudo demyx wp domain.tld core is-installed
  - sudo demyx exec domain.tld nx wget -qO- http://localhost | grep 'Hello world'
