# Demyx
# https://demyx.sh

notifications:
  email:
    on_success: never
    on_failure: never

services:
  - docker

env:
  - DEMYX_USERNAME=demyx DEMYX_REPOSITORY=openlitespeed

script:
  - docker build --no-cache -t demyx/"$DEMYX_REPOSITORY" tag-latest
  - docker build --no-cache -t demyx/"$DEMYX_REPOSITORY":bedrock tag-bedrock
  - docker-compose up -d
  - sleep 10
  - docker run -t --rm --volumes-from=demyx_wp --network=demyx demyx/wordpress:cli core install --url=http://domain.tld --title=demyx --admin_user=demyx --admin_password=demyx --admin_email=info@domain.tld --skip-email
  - docker run -t --rm --volumes-from=demyx_wp --network=demyx demyx/wordpress:cli core is-installed
