notifications:
  email:
    on_success: never
    on_failure: never

services:
  - docker

env:
  - DEMYX=demyx

before_install:
  - docker pull "$DEMYX"/docker-compose
  - docker pull "$DEMYX"/docker-socket-proxy
  - docker pull "$DEMYX"/mariadb:edge
  - docker pull "$DEMYX"/nginx
  - docker pull "$DEMYX"/ouroboros
  - docker pull "$DEMYX"/traefik
  - docker pull "$DEMYX"/utilities
  - docker pull "$DEMYX"/wordpress
  - docker pull "$DEMYX"/wordpress:cli
  - docker pull alpine

script:
  - export DEMYX_BUILD_DATE="$(date +%Y.%m.%d.%H%M%S)"
  - docker build --no-cache --build-arg DEMYX_BUILD="$DEMYX_BUILD_DATE" -t "$DEMYX"/"$DEMYX" .
  - mv chroot.sh /usr/local/bin/"$DEMYX"
  - chmod +x /usr/local/bin/"$DEMYX"
  - "$DEMYX" --nc
  - sleep 5
  - "$DEMYX" cmd install --domain=domain.tld --email=info@domain.tld --user="$DEMYX" --pass="$DEMYX"
  - "$DEMYX" restart --nc
  - "$DEMYX" cmd motd
  - "$DEMYX" cmd run domain.tld
  - "$DEMYX" cmd wp domain.tld core is-installed
