notifications:
  email: false

services:
  - docker

env:
  - DOCKER_COMPOSE_VERSION=1.24.1

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

jobs:
  include:
      script:
        - cd image/nginx-php-wordpress
        - docker build -t demyx/scratch .
        - docker-compose up -d
        - sleep 5
        - docker run -t --rm --volumes-from wp --network container:wp wordpress:cli core install --url="http://localhost" --title="demyx" --admin_user="demyx" --admin_password="demyx" --admin_email="info@domain.tld" --skip-email
        - docker exec -t wp sh -c "apk add curl; curl -I http://localhost; curl http://localhost | grep Welcome"

before_deploy:
  - echo "$DEMYX_PASSWORD" | docker login -u demyx --password-stdin
deploy:
  provider: script
  script: 
    - docker push demyx/scratch
    - cd image/nginx-php-wordpress
    - docker run --rm -v ./README.md:/data/README.md -e DOCKERHUB_USERNAME=demyx -e DOCKERHUB_PASSWORD="$DEMYX_PASSWORD" -e DOCKERHUB_REPO_PREFIX=demyx -e DOCKERHUB_REPO_NAME=scratch readme-to-hub
