sudo: required

dist: alpine

services:
  - docker

script:
  - docker build demyx/scratch .
  - docker run -t --rm $DOCKER_USERNAME/scratch sh -c 'nginx -V'

after_script:
  - docker images

before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
deploy:
  provider: script
  script: docker push demyx/scratch
  