services:
  - docker

jobs:
  include:
    #- stage: BrowserSync
      script:
        - cd image/nginx-php-wordpress
        - docker build -t demyx/nginx-php-wordpress .
        - docker run -dt --rm --name wp demyx/nginx-php-wordpress
        - sleep 5
        - curl -I wp
    #- stage: docker-compose
    #  script:
    #    - cd image/docker-compose
    #    - docker build -t demyx/docker-compose .
    #    - docker run -t --rm demyx/docker-compose --version

#script:
#  - cat /etc/os-release
#  - echo "$DEMYX_PASSWORD" | docker login -u demyx --password-stdin
#  - docker build -t demyx/scratch .
#  - docker run -dt --name demyx -v /var/run/docker.sock:/var/run/docker.sock demyx/scratch
#  - sleep 5
#  - docker exec -t demyx demyx motd

#after_script:
#  - docker images

#before_deploy:
#  - echo "$DEMYX_PASSWORD" | docker login -u "$DEMYX_USERNAME" --password-stdin
#deploy:
#  provider: script
#  script: docker push "$DEMYX_USERNAME"/scratch
