# Demyx
# https://demyx.sh

notifications:
  email:
    on_success: never
    on_failure: never

services:
  - docker

script:
  - docker build -t demyx/openlitespeed tag-latest
  - docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock dslim/docker-slim build --continue-after=enter demyx/openlitespeed
