# Demyx
# https://demyx.sh

notifications:
  email:
    on_success: never
    on_failure: never

services:
  - docker

env:
  - DEMYX_USERNAME=demyx DEMYX_REPOSITORY=elgg

script:
  - docker build -t demyx/"$DEMYX_REPOSITORY" .
  - docker-compose up -d demyx_db
  - sleep 5
  - docker-compose up -d demyx_elgg
  - sleep 30
  - docker logs demyx_elgg
  - docker ps
  - docker exec -t demyx_elgg sh -c "php vendor/bin/elgg-cli plugins:list --status all"
