sudo: required

dist: alpine

services:
  - docker

script:
  - docker build -t demyx/scratch .
  - docker run -t --rm $DEMYX_USERNAME/scratch nginx -V

after_script:
  - docker images

before_deploy:
  - echo "$DEMYX_PASSWORD" | docker login -u "$DEMYX_USERNAME" --password-stdin
deploy:
  provider: script
  script: docker push "$DEMYX_USERNAME"/scratch
