# Demyx
# https://demyx.sh

notifications:
  email:
    on_success: never
    on_failure: never

services:
  - docker

env:
  - DEMYX_USERNAME=demyx DEMYX_REPOSITORY=scratch

script:
  - which docker
  - which sed
  - which cat
  - which grep
  - which cut
  - which git
  - which curl
  - which jq
  - which awk
  - which head