notifications:
  email: false

services:
  - docker

env:
  - DOCKER_COMPOSE_VERSION=1.24.1

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

jobs:
  include:
    #- stage: BrowserSync
      script:
        - cd image/nginx-php-wordpress
        - docker build -t demyx/nginx-php-wordpress .
        #- docker run -dt --rm --name wp --network host demyx/nginx-php-wordpress
        - docker-compose up -d
        - sleep 10
        - docker run -t --rm --volumes-from wp wordpress:cli core install --url="http://localhost" --title="demyx" --admin_user="demyx" --admin_password="demyx" --admin_email="info@localhost" --skip-email
        #- docker exec -t wp sh -c "cat wp-config.php"
        - sleep 5
        - docker exec -t wp sh -c "apk add curl; curl -I http://localhost; cat wp-config.php"
    #- stage: docker-compose
    #  script:
    #    - cd image/docker-compose
    #    - docker build -t demyx/docker-compose .
    #    - docker run -t --rm demyx/docker-compose --version

#script:
#  - cat /etc/os-release
#  - echo "$DEMYX_PASSWORD" | docker login -u demyx --password-stdin
#  - docker build -t demyx/scratch .
#  - docker run -dt --name demyx -v /var/run/docker.sock:/var/run/docker.sock demyx/scratch
#  - sleep 5
#  - docker exec -t demyx demyx motd

#after_script:
#  - docker images

#before_deploy:
#  - echo "$DEMYX_PASSWORD" | docker login -u "$DEMYX_USERNAME" --password-stdin
#deploy:
#  provider: script
#  script: docker push "$DEMYX_USERNAME"/scratch
