notifications:
  email:
    on_success: never
    on_failure: never

services:
  - docker

env:
  - DEMYX_USERNAME=demyx DEMYX_REPOSITORY=demyx

before_install:
  - docker pull demyx/docker-compose
  - docker pull demyx/docker-socket-proxy
  - docker pull demyx/mariadb:edge
  - docker pull demyx/nginx
  - docker pull demyx/ouroboros
  - docker pull demyx/traefik
  - docker pull demyx/utilities
  - docker pull demyx/wordpress
  - docker pull demyx/wordpress:cli
  - docker pull alpine

script:
  - export DEMYX_BUILD_DATE="$(date +%Y.%m.%d.%H%M%S)"
  - docker build --no-cache --build-arg DEMYX_BUILD="$DEMYX_BUILD_DATE" -t demyx/"$DEMYX_REPOSITORY" .
  #- sudo mv chroot.sh /usr/local/bin/demyx
  #- sudo chmod +x /usr/local/bin/demyx
  - sudo bash chroot.sh --nc
  - sleep 5
  - docker exec -t demyx install --domain=domain.tld --email=info@domain.tld --user="$DEMYX_REPOSITORY" --pass="$DEMYX_REPOSITORY"
  - sudo bash chroot.sh restart --nc
  - sleep 5
  - docker exec -t demyx cmd motd
  - docker exec -t demyx cmd run domain.tld --ssl=false
  - docker logs demyx
  - sudo bash chroot.sh --nc cmd wp domain.tld core is-installed
