sudo: required

dist: alpine

services:
  - docker

script:
  - echo "$DEMYX_PASSWORD" | docker login -u "$DEMYX_USERNAME" --password-stdin
  - docker build -t demyx/scratch .
  - docker run --rm $DEMYX_USERNAME/scratch /usr/local/bin/demyx run domain.tld --cache

after_script:
  - docker images

before_deploy:
  - echo "$DEMYX_PASSWORD" | docker login -u "$DEMYX_USERNAME" --password-stdin
deploy:
  provider: script
  script: docker push "$DEMYX_USERNAME"/scratch
