dist: alpine

jobs:
  include:
    - stage: build docker image
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker build -t demyx/scratch .
    - stage: test
      script: 
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker run -t --rm $DOCKER_USERNAME/scratch "nginx -V"
    - stage: push
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push $DOCKER_USERNAME/scratch
