version: "3.7"

services:
  db:
    image: demyx/mariadb
    restart: unless-stopped
    networks:
      - demyx
    volumes:
      - elgg_db:/var/lib/mysql
    environment:
      MARIADB_DATABASE: demyx_db
      MARIADB_USERNAME: demyx_user
      MARIADB_PASSWORD: demyx_password
      MARIADB_ROOT_PASSWORD: demyx_root_password
  elgg:
    image: demyx/elgg
    restart: unless-stopped
    networks:
      - demyx
    volumes:
      - elgg:/var/www/html
    environment:
      ELGG_DOMAIN: domain.tld
      TZ: America/Los_Angeles
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:domain.tld,www.domain.tld"
      - "traefik.port=80"
volumes:
  elgg:
    name: elgg
  elgg_db:
    name: elgg_db
networks:
  demyx:
    name: demyx
