version: "3.7"

services:
  db:
    container_name: db
    image: demyx/mariadb
    restart: unless-stopped
    networks:
      - demyx_network
    volumes:
      - demyx_db:/var/lib/mysql
    environment:
      MARIADB_DATABASE: demyx_db
      MARIADB_USERNAME: demyx_user
      MARIADB_PASSWORD: demyx_password
      MARIADB_ROOT_PASSWORD: demyx_root_password
  wp:
    container_name: wp
    image: demyx/nginx-php-wordpress
    restart: unless-stopped
    networks:
      - demyx_network
    volumes:
      - demyx_wp:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: demyx_db
      WORDPRESS_DB_USER: demyx_user
      WORDPRESS_DB_PASSWORD: demyx_password
      TZ: America/Los_Angeles
volumes:
  demyx_wp:
    name: demyx_wp
  demyx_db:
    name: demyx_db
networks:
  demyx_network:
    name: demyx_network
